### ISSUE TITLE
Fill:"None" ignored

### ISSUE THREAD

**Issue by Eloreden** [mchoe/SwiftSVG#112]
As this post say https://github.com/mchoe/SwiftSVG/issues/48 

i have a same issue

Something go wrong with fill="none" because not run...

`<path fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" d="M455.3,58.7c-38.2-18.6-71.5-19-79.8-18.7c-8.3-0.2-41.6,0.2-79.8,18.7c-44.2,21.5-68,94.5-68,120.7 c0,20.8,6.3,39.9,23.8,46.5c31.3,11.8,98.4,27.2,124,27.2s92.7-15.4,124-27.2c17.5-6.6,23.8-25.7,23.8-46.5 C523.3,153.2,499.5,80.2,455.3,58.7z"/>`

**Comment by mchoe** [comment]
This is addressed in v2.3.1

**Comment by ggua5470** [comment]
I am using the v2.3.2, and when a svg has fill="none" (e.g. the one below), it fills black color.
https://cdn.shopify.com/s/files/1/0496/1029/files/Freesample.svg

I have to add fill-opacity="0" to make it work.

The one without fill="none" works ok:
https://raw.githubusercontent.com/efc/SwiftSVG/master/SwiftSVGExamples/hawaiiFlowers.svg
