### ISSUE TITLE
Is `use` element supported?

### ISSUE THREAD

**Issue by valeriyvan** [mchoe/SwiftSVG#128]
Would be nice to have clear lists of supported and not supported features.
Instead of just ignoring not supported elements parser would at least issue a log message.

**Comment by mchoe** [comment]
Unfortunately `<use>` is not supported. For now, these are the elements that are supported: `<svg>`, `<g>`, `<path>`, `<circle>`, `<ellipse>`, `<line>`, `<polygon>`, `<polyline>`, and `<rect>`
