### ISSUE TITLE
tvOS support?

### ISSUE THREAD

**Issue by taschmidt** [mchoe/SwiftSVG#132]
I'd love to use this lib but the podspec doesn't support tvOS. Is this on the horizon?

**Comment by vari** [comment]
Although tvOS support has been added to the podspec file on the master branch, there is no release of SwiftSVG that includes tvOS support. 

@mchoe is there an ETA for when a new release with tvOS support will be available? If no release is planned, can you consider releasing a patch version with tvOS support? Thanks!
