### ISSUE TITLE
SwiftUI examples

### ISSUE THREAD

**Issue by corykacal** [mchoe/SwiftSVG#164]
I am having trouble using SwiftSVG with SwiftUI. I am new to SwiftUI and iOS development and don't know where to start with SwiftSVG. Can someone add SwiftUI examples alongside the story board ones? Thank you!

**Comment by mchoe** [comment]
Hi @corykacal, SwiftSVG currently doesn't have SwiftUI support out of the box. You can probably still add it yourself like any UIView by adding conformance to `UIViewRepresentable` and managing a `SVGView`. I would recommend starting with searching for `UIViewRepresentable` and looking through the tutorials that pop up.

I do plan on adding SwiftUI support and I'll let you know once that gets added.
