### ISSUE TITLE
Is there a way to parse layer path back to string path?

### ISSUE THREAD

**Issue by gouen95** [mchoe/SwiftSVG#170]
Hi, I wanna know if there's a way to parse layer path back to string path such as "M75 0 l75 200 L0 200 Z"?

The reason for this is that I wanted to create a shape in my app and convert it into SVG string, and vice-versa.

Any help would be greatly appreciated! :D

**Comment by mchoe** [comment]
Hi @gouen95, sorry there's no way to do that right now.
