### ISSUE TITLE
No support for Elliptical Arc

### ISSUE THREAD

**Issue by pcbeard** [mchoe/SwiftSVG#19]
See https://www.w3.org/TR/SVG/implnote.html#ArcImplementationNotes

When a path contains an "A" or "a" command the parser simply asserts.

**Comment by pcbeard** [comment]
SVGKit has a parser for this.

**Comment by xZeroMCPE** [comment]
https://github.com/BukkitPE/BukkitPE

**Comment by xZeroMCPE** [comment]
Oops, sorry. I've posted this by mistake. 

But, mind checking it out? :P

**Comment by akilachen** [comment]
When a path contains an "A" or "a" command the parser simply asserts.

can't work

**Comment by mchoe** [comment]
Closing in support of #85.
