### ISSUE TITLE
Issue with cocoapod in Xcode 8.2.1 on iOS project

### ISSUE THREAD

**Issue by bryanbartow** [mchoe/SwiftSVG#29]
Anyone else getting an error in ```NSBezierPath+CrossPlatform.swift``` because of the attempt to import AppKit? It seems to me the class should be wrapped in
```
#if os(OSX)
#endif
```
Am I wrong?

**Comment by jsawruk** [comment]
Yes, I am getting the same issue. Wrapping it in the #if/#endif that you recommend worked. Maybe you should submit a pull request.

**Comment by bryanbartow** [comment]
@jsawruk I'd like to hear from one of the project owners first. I'm assuming they did that intentionally and there has been a recent breaking change with Xcode and/or cocoapods. If not, I'll submit a PR.

**Comment by jsawruk** [comment]
Agreed. I hope they can address this quickly. I would really like to use this library. I doubt it's a change to cocoapods, but I cannot rule out a change to Xcode.

**Comment by mchoe** [comment]
I added the preprocessor directive. Thanks for pointing it out and you should be good to go.
