### ISSUE TITLE
Does not work with color on path

### ISSUE THREAD

**Issue by Shakarang** [mchoe/SwiftSVG#30]
Hi,

The view does not render anything when I add a color on the path.

I've also tried with your [example](https://github.com/efc/SwiftSVG/blob/master/SwiftSVGExamples/hawaiiFlowers.svg) and it is the same result.

It works fine when I remove the ```fill``` attribute.

**Comment by mchoe** [comment]
Hi @Shakarang, this is now supported in v2.0.0. Please use that version.
