### ISSUE TITLE
<rect> tags not handled

### ISSUE THREAD

**Issue by PierreMardon** [mchoe/SwiftSVG#31]
It seems `<rect>` tags aren't part of the UIBezierPath when I parse the SVG file below :

Expected rendering : 
<img width="24" alt="capture d ecran 2017-02-23 a 19 16 29" src="https://cloud.githubusercontent.com/assets/327473/23272712/9e65cb92-f9fc-11e6-9019-0f195e05d33f.png">

Renders : 
<img width="47" alt="capture d ecran 2017-02-23 a 19 19 11" src="https://cloud.githubusercontent.com/assets/327473/23272812/fdb06a9e-f9fc-11e6-886a-16149e2adde4.png">

```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 17.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="31.18px" height="31.18px" viewBox="0 0 31.18 31.18" enable-background="new 0 0 31.18 31.18" xml:space="preserve">
<rect x="8.621" y="11.809" width="0.875" height="7.688"/>
<rect x="10.121" y="11.809" width="0.875" height="7.688"/>
<rect x="20.184" y="11.809" width="0.875" height="7.688"/>
<rect x="21.684" y="11.809" width="0.875" height="7.688"/>
<path d="M15.574,12.783c-2.615,0-4.734,1.285-4.734,2.87s2.12,2.87,4.734,2.87s4.734-1.285,4.734-2.87S18.189,12.783,15.574,12.783z
	 M16.942,17.784c-0.948,0.608-2.328,0.147-3.084-1.03c-0.755-1.177-0.6-2.625,0.348-3.233s2.328-0.147,3.084,1.03
	C18.046,15.728,17.89,17.176,16.942,17.784z"/>
</svg>
```

**Comment by SuperWomble** [comment]
I'm also seeing this behaviour with SVGs created in Sketch. To replicate: just add a rect to the artwork in Sketch. Then Export as SVG. The rect is not drawn by SwiftSVG.

**Comment by mchoe** [comment]
Unfortunately, `<rect>` and other shape tags aren't supported right now. If you want to draw shapes, you will have to convert them to `<path>` tags.

I expect to support shapes soon though. No definite timeline right now, but soon-ish the way things have been going so far.

**Comment by PierreMardon** [comment]
Thanks for your answer !
