### ISSUE TITLE
CAShapeLayer has nil path

### ISSUE THREAD

**Issue by SuperWomble** [mchoe/SwiftSVG#33]
Given the following code, with a known good URL to the test flowers .svg file:

```
if let url =  Bundle.main.url(forResource: "hawaiiFlowers", withExtension: "svg")
    let shape = CAShapeLayer(SVGURL: url)
    assert(shape.cgPath != nil, "CAShapeLayer has no path!")  // <-- ERROR HERE.
}
```

The problem occurs with other .svg files as well. It appears that `CAShapeLayer` path is not being set. I don't fully understand the constructor code, but it appears that the path is not being set from the parser.

The good news is that the same code on `UIBezierPath` _does_ work. (The downside that no fill/stroke attributes are being recorded with a UIBezierPath, making this method of limited use for drawing SVGs with multiple color elements.)

```
let maybeBezier = UIBezierPath.pathWithSVGURL(url)
if let bezier = maybeBezier {
        assert(bezier.cgPath != nil, "UIBezierPath has no path!")  // no error here
}
```

Also, a suggestion: the `CAShapeLayer` constructor should be failable, and return an Optional.

e.g.  

```
guard let shape = CAShapeLayer(SVGURL: url) else {
    print("Failed to create CAShapeLayer from URL \(url)")
    return
}
```

Thanks again for all your work.

**Comment by mchoe** [comment]
Hi @SuperWomble, this example now works completely in v2.0.0.
