### ISSUE TITLE
No resizing option

### ISSUE THREAD

**Issue by rostopira** [mchoe/SwiftSVG#36]
What the point of using vector graphics, which you couldn't scale?
The most important part - respecting content mode (scale to fill, center, aspect to fit)

**Comment by amagain** [comment]
I too could not find a resizing option. How can we achieve it?

**Comment by mchoe** [comment]
This is now supported in v2.0.0 and can use `func resizeToFit(_ rect: CGRect)` on `SVGLayer` to accomplish this.
