### ISSUE TITLE
SVG to bezier will not work

### ISSUE THREAD

**Issue by Curnelius** [mchoe/SwiftSVG#39]
No matter what we try it will draw only the **first line of the artwork** 

 
```
        let svgURL = Bundle.main.url(forResource: "sunglasses", withExtension: "svg")
        let pathFromSVGFile = UIBezierPath.pathWithSVGURL(svgURL!)!
        UIColor.blue.setStroke()
        pathFromSVGFile.lineWidth = 3
        pathFromSVGFile.stroke()
        shapeLayer.path = pathFromSVGFile.cgPath
        self.view.layer.addSublayer(shapeLayer)
```

Where the exact same file works if we use the shape layer directly.

`let svgShapeLayerFromFile = CAShapeLayer(SVGURL: svgURL!)`  //will work

**Comment by mchoe** [comment]
Can you paste the SVG source here so I can test the file? There is a very big update coming very soon and hopefully that will solve your problem. I just want to make sure it addresses the issue.

**Comment by mchoe** [comment]
Hi @Curnelius, please try this under the new 2.0.0 release and if your problem still exists, you can reopen this issue. Thanks.
