### ISSUE TITLE
Support implicit command repetition

### ISSUE THREAD

**Issue by pwesten** [mchoe/SwiftSVG#42]
Per the SVG 1.1 spec:

"The command letter can be eliminated on subsequent commands if the same command is used multiple times in a row (e.g., you can drop the second "L" in "M 100 200 L 200 100 L -100 -200" and use "M 100 200 L 200 100 -100 -200" instead)."

**Comment by mchoe** [comment]
This should work in the current implementation. See screenshot below.

![example](https://user-images.githubusercontent.com/2816885/28197218-6b5aba74-6823-11e7-89fb-e32795a15355.png)

Having said that, I will be releasing a brand new version very soon (within the week hopefully) which features a test-driven parser that supports more elements and attributes. You can preview that release on the `feature/2.0.0` branch. It's still changing, so I wouldn't recommend using it in production yet, but I know for a fact that consecutive commands is fully supported.
