### ISSUE TITLE
Support for swift 2.3

### ISSUE THREAD

**Issue by sujayun** [mchoe/SwiftSVG#45]
I have my full project in Swift 2.3 and I can't upgrade it to Swift3

I am not able to use this library as its in Swift 3 and getting nearly 80 errors.

So u upload the previous swift 2.3 version of this library

**Comment by mchoe** [comment]
Hi sujayun, you can use release 1.1.5 which supports Swift 2.x. You can specify the version number in cocoapods or carthage.
