### ISSUE TITLE
SVG Resize to Fit in rect

### ISSUE THREAD

**Issue by sujayun** [mchoe/SwiftSVG#47]
I got this function to return my view with filled color
Fill color is not working 
Image becomes too big and how do I resize this to fit in rect

func GetSvgViewFnc(SvgImgFileVar: String, ClrVar: UIColor) -> UIView
{
    let svgURL = NSBundle.mainBundle().URLForResource(SvgImgFileVar, withExtension: "svg")
    let svgShpLyrVar = CAShapeLayer(SVGURL: svgURL!)
    svgShpLyrVar.fillColor = ClrVar.CGColor
    svgShpLyrVar.bounds = CGRect(x: 0,y: 0,width: 24,height: 24)
    let SvgVyu = UIView(frame: CGRect(x: 0,y: 0,width: 24,height: 24))
    SvgVyu.layer.addSublayer(svgShpLyrVar)
    return SvgVyu
}

**Comment by mchoe** [comment]
This is supported in v2.0.0
