### ISSUE TITLE
fill none is not considered

### ISSUE THREAD

**Issue by sujayun** [mchoe/SwiftSVG#48]
Your code is not considering fill None to the path.
It's filling fully

```
<path style="fill:none;stroke:#000000;" 
		d="M90,66c0,2-2,4-4,4H14c-2,0-4-2-4-4V34c0-2,2-4,4-4h72c2,0,4,2,4,4V66z"/>

|OR|

<path fill="none" stroke="#000000"
		d="M90,66c0,2-2,4-4,4H14c-2,0-4-2-4-4V34c0-2,2-4,4-4h72c2,0,4,2,4,4V66z"/>
```

**Comment by mchoe** [comment]
This is supported in v2.0.0.

**Comment by Eloreden** [comment]
Something go wrong with fill="none" because not run...
<path fill="none" stroke="#000000" stroke-width="2" stroke-miterlimit="10" d="M455.3,58.7c-38.2-18.6-71.5-19-79.8-18.7c-8.3-0.2-41.6,0.2-79.8,18.7c-44.2,21.5-68,94.5-68,120.7
			c0,20.8,6.3,39.9,23.8,46.5c31.3,11.8,98.4,27.2,124,27.2s92.7-15.4,124-27.2c17.5-6.6,23.8-25.7,23.8-46.5
			C523.3,153.2,499.5,80.2,455.3,58.7z"/>
