### ISSUE TITLE
Great! Here are some SVG assets I made in Inkscape for you to use!

### ISSUE THREAD

**Issue by Emasoft** [mchoe/SwiftSVG#6]
Great work! I really hope that you can provide us with a fully SVG 1.1 compatible library!

Feel free to use some of my SVG assets for your demos (I made them in Inkscape):

![ios_app_buttons](https://cloud.githubusercontent.com/assets/713559/5924670/d56b48a0-a65d-11e4-95b4-7377a6b7eda9.png)

You can download the original svg file from my google drive (click on the download button):
http://goo.gl/m7TbmM

Feel free to use them, but check the fonts.. I use some fonts not on iOS by default, you should install them with the app, or replacing them with similar fonts

For an easier debug, here it is a splitted version of the two main buttons svg files, you can download the zip from here: 
https://drive.google.com/file/d/0BxexooDWEb8ublZlcm5yRWpXTzQ/view?usp=sharing

If you need other SVG assets for your lib, tell me! I will do them for you at no cost. If your lib development will be completed it will save me a lot of time! :)

**Comment by mchoe** [comment]
Thanks for sending the assets along! I want to keep the examples simple, so as they're easier to follow, but once I include support for more of the specification, I'll keep these in mind.
