### ISSUE TITLE
Can I use this library with Objective C ?

### ISSUE THREAD

**Issue by sriteja25** [mchoe/SwiftSVG#65]
I have an objective C project in which I want to use this project. Is there a way to manually install this Library ?

**Comment by buguibu** [comment]
I'm using it right now
`
@import SwiftSVG;
//....
-(void) setSwiftSVG
{
    SVGView *svgView = [SVGView new];
    [svgView setSVGName:@"sample"];
    [svgView setFrame:self.bounds];
    [self addSubview:svgView];
}
`

**Comment by mchoe** [comment]
Hi @sriteja25, you can use the library with Objective-C. Thank you @buguibu for the example!

You may want to check that your Cocoapods version is using the the right Swift Version in your build settings.
