### ISSUE TITLE
carthage build frameworks failed for macOS.

### ISSUE THREAD

**Issue by ACChe** [mchoe/SwiftSVG#66]
`Failed to write to /Users/A/X/Carthage/Build/Mac/SwiftSVG.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “SwiftSVG.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/A/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/SwiftSVG/v2.1.2/Build/Intermediates.noindex/ArchiveIntermediates/SwiftSVG/BuildProductsPath/Release-iphoneos/SwiftSVG.framework, NSFilePath=/Users/A/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/SwiftSVG/v2.1.2/Build/Intermediates.noindex/ArchiveIntermediates/SwiftSVG/BuildProductsPath/Release-iphoneos/SwiftSVG.framework, NSUnderlyingError=0x7fe879d65390 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

Is it support macOS?

**Comment by afedor** [comment]
This is fixed with #77

**Comment by ACChe** [comment]
OK, let me check it , Thanks.

**Comment by mchoe** [comment]
@ACChe: Were you able to install with Carthage?
