### ISSUE TITLE
[Question] How to change image size after load?

### ISSUE THREAD

**Issue by 6pm** [mchoe/SwiftSVG#68]
I added svg image and I want сhange size. It is possible?

**Comment by mchoe** [comment]
Hi @6pm, so The `UIView` and `CALayer` interfaces allow you to specify a completion block after the SVG has been rendered. They both pass the `SVGLayer` which you can further change however you want, including changing the size. The library also provides a `func resizeToFit(_ rect: CGRect)` function that allows you to resize to whatever you want.

Check out the hammock example on the readme to see how you can do this.
