### ISSUE TITLE
SVGView: Rendering (Preview) isn't working, can't resize

### ISSUE THREAD

**Issue by anonym24** [mchoe/SwiftSVG#71]
Rendering (Preview) isn't working (I tested on the original example project from github), image only appear on real or simulator device, but not in Xcode

![screenshot_2](https://user-images.githubusercontent.com/8851301/35227782-a8747542-ff97-11e7-8e2d-d18f5d8a9161.png)

Also how can we resize the image? I though it would be the same as UIView size, but it can be smaller than UIView size or even bigger (out of bounds), so seems SVGView is quite useless here, it just shows original SVG file resolution

Would be better if image could take all space of UIView (not bigger) and also saved its aspect ratio and also so we could set different behaviour like for ImageView in Android

**Comment by mchoe** [comment]
I think this is related to #44. Closing in favor of the older ticket.
