### ISSUE TITLE
Crashes for some of the SVGs

### ISSUE THREAD

**Issue by anoop4real** [mchoe/SwiftSVG#72]
Thread 12: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

at

```
    internal func execute(on path: UIBezierPath, previousCommand: PreviousCommand? = nil) {
        
        if previousCommand is MoveTo {
            var implicitLineTo = LineTo(pathType: self.pathType)
            implicitLineTo.coordinateBuffer = [self.coordinateBuffer[0], self.coordinateBuffer[1]]
            implicitLineTo.execute(on: path)
            return
        }
        
        let point = self.pointForPathType(CGPoint(x: self.coordinateBuffer[0], y: self.coordinateBuffer[1]), relativeTo: path.currentPoint)
        path.move(to: point)
    }
```

**eg; https://restcountries.eu/data/dza.svg**

**Comment by mchoe** [comment]
Hi @anoop4real, a couple of things are going on here. 

First, the crash is from the parser's inability to render numbers with an `a` in the format string. In the example you included, the crash is at the first path when it's trying to render `28a8` in the `clipPath` element. I'm not exactly sure of that number format, so can you please tell me the source of the image? Did you get the image from the web or did you generate it yourself? If you generated it, what was the program that you used?

The second issue is with the `<clipPath>` element. Unfortunately, SwiftSVG doesn't support clip paths now, so even if it could render the number, the SVG still wouldn't render properly. I'm going to add a ticket to investigate adding this functionality in the future.

Thanks for filing the ticket though, and I'm going to replace this one with investigating `<clipPath>` support.

**Comment by mchoe** [comment]
Dupe of #53

**Comment by anoop4real** [comment]
Hello @mchoe ,

This image is available from the free api https://restcountries.eu/ which gives the flag of all countries. I havent created it, it is the flag of Algeria I guess. In android I use https://github.com/ar-android/AndroidSvgLoader and it works fine. Hope you find a fix for this, I feel this library is lightweight compared to macaw.
