### ISSUE TITLE
(Suggestion) Pattern support

### ISSUE THREAD

**Issue by buguibu** [mchoe/SwiftSVG#80]
I can't draw a stripped pattern defined like this:

`<pattern height="8" id="diagonal-stripes" patternTransform="rotate(60)" patternUnits="userSpaceOnUse" width="8" x="0" y="0">   <rect height="8" style="stroke:none; fill:#cdd4d8;" width="3" x="0" y="0"/></pattern>`

used in this way:

`<path d="..." id="1870b04c-0503-4906-a9c7-b844ed2d2f10" style="fill: url(#diagonal-stripes)"/>`.

Seems like _fill_ only accepts hexadecimal colours as value.

**Comment by mchoe** [comment]
Yes, fill color accepts hex values and named values for now. While patterns aren't supported now, I'm going to file this as an enhancement and something to consider. Thanks for filing the ticket.

**Comment by buguibu** [comment]
A progress:
```
func diagonalStripe(_ aThing: String) {
        self.svgLayer.fillColor = UIColor(patternImage: #imageLiteral(resourceName: "pattern")).cgColor
}
```
