### ISSUE TITLE
Invalid stroke color

### ISSUE THREAD

**Issue by ymkim50** [mchoe/SwiftSVG#86]
/// Applies the given stroke color to all `CAShapeLayer`s
    override open var strokeColor: CGColor? {
        didSet {
            self.applyOnSublayers(ofType: CAShapeLayer.self) { (thisShapeLayer) in
                thisShapeLayer.strokeColor = fillColor
            }
        }
    }

I set stroke color, but it's invalid colored. I think code will below:
    /// Applies the given stroke color to all `CAShapeLayer`s
    override open var strokeColor: CGColor? {
        didSet {
            self.applyOnSublayers(ofType: CAShapeLayer.self) { (thisShapeLayer) in
                thisShapeLayer.strokeColor = strokeColor
            }
        }
    }

**Comment by shaps80** [comment]
I've submitted PR #91 for this however if you read my comments there are some caveats.
