### ISSUE TITLE
Feature request: layer ID in SVGLayer

### ISSUE THREAD

**Issue by pavelgubarev** [mchoe/SwiftSVG#90]
Hi there!

I would like to be able to have 'id' property parsed from SVG into SVGLayer.

`<path id="ground" fill="#748E25" stroke="#000000" stroke-width="3" stroke-miterlimit="10" d="M1041.5,1481`

and then have something like

`print(mySVGLayer.id)
`
Maybe it is already done but I haven't found it.

Cheers!

**Comment by mchoe** [comment]
Hi @pavelgubarev, yes this feature is already available. For `SVGShapeElement`s and `SVGGroup`s (which includes `<g>` and the root `<svg>` elements), the `id` attribute sets the underlying `SVGLayer`'s name property. This is the same as `CALayer`'s name property and you can see the documentation for it here: [https://developer.apple.com/documentation/quartzcore/calayer/1410879-name](https://developer.apple.com/documentation/quartzcore/calayer/1410879-name)
