### ISSUE TITLE
Is Swift SVG support Animation? how is it compare to Macaw?

### ISSUE THREAD

**Issue by steve21124** [mchoe/SwiftSVG#93]
Thanks for the library. from readme, it is for high performance svg parser. Does SwiftSVG support animation? how it is compare to Macaw https://github.com/exyte/Macaw ? I try to see if I need animation of svg as uiview on top of existing uiview. Will Swift SVG support it?

**Comment by mchoe** [comment]
Hi @steve21124, SwiftSVG does not support animations and it probably will not in the near future. The library isn't meant to be a full-featured SVG library and tries to focus on a limited, but rich, set of use cases. Unfortunately, animations isn't one of those categories.

I would recommend looking into Macaw as it seems to support animations quite nicely.
